### ISSUE TITLE
Wrong link in Instant Deployment

### ISSUE THREAD

**Issue by omahonyb** [sophos-iaas/aws-cf-templates#19]
FYI the link is wrong. 
eg https://s3.amazonaws.com/sophos-nsg-cf/utm/ha_standalone.template should be https://s3.amazonaws.com/sophos-nsg-cf/utm/utm-latest-ha_standalone.template

I was planning on using sophos as the Hub for a transit VPC when I came across this CF template. It has been really handy [although a /16 was too big for my liking, and modified it down to /20]
B

**Comment by GeorgFleig** [comment]
Hello omahonyb,

thank you for bringing this issue to our attention. We have fixed the broken links and the instant deployment procedure.

I hope you are enjoying our products and I'm glad to hear the Sophos UTM on AWS is helpful to your use case.

Best regards,
Georg Fleig
